[build]
  command = "go build -o bin/signtools main.go"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  GO_IMPORT_PATH = "github.com/SignTools/SignTools"
